EarthBnbMVC/Models/ErrorViewModel.cs
namespace EarthBnbMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EarthBnbMVC/Models/Listing.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EarthBnbMVC.Models
{
    public class Listing
    {

        [Required]
        public int Id { get; set; }

        public string Location { get; set; }

        public int MaxGuests { get; set; }

        public int NightCost { get; set; }

        public DateTime DateOfBirth { get; set; }
        public DateTime AvailableDates { get; set; }

        public float StarScore { get; set; }

        public int Bedrooms { get; set; }

        public int ServiceFee { get; set; }

        public string Description { get; set; }
    }
}

EarthBnbMVC/Models/Listings.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EarthBnb.Models
{
    public class Listings
    {

        [Required]
        public int Id { get; set; }

        public string Location { get; set; }

        public int MaxGuests { get; set; }

        public int NightCost { get; set; }

        public DateTime DateOfBirth { get; set; }
        public DateTime AvailableDates { get; set; }

        public float StarScore { get; set; }

        public int Bedrooms { get; set; }

        public int ServiceFee { get; set; }

        public string Description { get; set; }
    }
}

EarthBnbMVC/Controllers/HomeController.cs
using EarthBnbMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EarthBnbMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EarthBnbMVC/Controllers/ListingController.cs
using EarthBnbMVC.Models;
using Microsoft.AspNetCore.Mvc;

namespace EarthBnbMVC.Controllers
{
    public class ListingController : Controller
    {
        private static List<Listing> listings = new List<Listing>();
        
        public IActionResult Index()
        {
            return View(listings);
        }

        public IActionResult Create()
        {
            var listing = new Listing();
            return View(listing);
        }

        public IActionResult CreateListing(Listing listing)
        {
            listings.Add(listing);
            return RedirectToAction(nameof(Index));
        }
    }
}

EarthBnbMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1>Welcome to the EarthBnb Homepage</h1>
</div>

EarthBnbMVC/Views/Listing/Create.cshtml
@model EarthBnbMVC.Models.Listing

<h1>Create Listing</h1>

<hr />

<div class="row">
    <div class="col-6">

        <div class="card">
            <div class="card-header">
                <h5>Add a Listing</h5>
            </div>
            <div class="card-body">
                <form asp-controller="Listing" asp-action="CreateListing" method="post">
                    <div class="mb-3">
                        <label class="form-label">Location</label>
                        <input asp-for=Location type="text" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Price per Night</label>
                        <input asp-for=NightCost type="text" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Description</label>
                        <input asp-for=Description type="textarea" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</div>

EarthBnbMVC/Views/Listing/Index.cshtml
@model List<EarthBnbMVC.Models.Listing>

<h1>Listing Index View</h1>

<ul>
    @foreach (var listing in Model)
    {
        <li>@listing.Location</li>
        <li>@listing.NightCost</li>
        <li>@listing.Description</li>
    }
</ul>

EarthBnbMVC/Views/Listings/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<hr />

<div class="row">
    <div class="col-6">

        <div class="card">
            <div class="card-header">
                <h5>Add a Listing</h5>
            </div>
            <div class="card-body">
                <form asp-controller="Listing" asp-action="CreateListing" method="post">

                    <div class="mb-3">
                        <label class="form-label">Title</label>
                        <input asp-for=Name type="text" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Price</label>
                        <input asp-for=Age type="number" class="form-control" />
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Save</button>
                    </div>
                </form>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
</div>

EarthBnbMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Earthbnb</title>
    <link rel="icon" href="~/images/browser-logo.png" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EarthBnb.styles.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <script src="https://kit.fontawesome.com/07a0766043.js" crossorigin="anonymous"></script>
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-expand-md navbar-dark" aria-label="Fourth navbar example">
            <div class="container-fluid">
                <div class="logo-link">
                    <a class="navbar-brand logo text-white" asp-area="" asp-controller="Home" asp-action="Index">
                        <i class="fas fa-2x fa-globe-americas"></i><div class="logo-text">earthbnb</div>
                    </a>
                </div>
                <div class="navbar-collapse collapse" id="navbarsExample04" style="">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area=""  asp-page="/Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Listing" asp-action="Index">Listings</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown" aria-expanded="false">Login</a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Settings</a></li>
                            </ul>
                        </li>
                    </ul>
                    <form role="search">
                        <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; <span id="fullYear"></span> <a id="privacyLink" asp-page="/Index">EarthBnb</a> <a id="privacyLink" sp-area="" asp-page="/Privacy"> - Privacy</a>
        </div>
    </footer>
    <script>
        const d = new Date();
        let fullYear = d.getFullYear();
        document.getElementById("fullYear").innerHTML = fullYear
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>